- app.js
- controllers/UserController.js
- controllers/postController.js
- controllers/validators/appValidator.js
- controllers/validators/generalSearch.js
- controllers/validators/index.js
- controllers/validators/objectTypeValidator.js
- controllers/validators/postValidator.js
- controllers/validators/userValidator.js
- controllers/validators/wobjectValidator.js
- controllers/wobjController.js
- models/PostModel.js
- package.json
- utilities/helpers/customValidationHelper.js
- utilities/helpers/index.js
- utilities/operations/post/getPostsByCategory.js
- utilities/operations/user/getUserFeed.js
- utilities/operations/wobject/getPostsByWobject.js
add param lastId for mongoose _id on user feed/posts by category/wobjects feed, to avoid duplicate posts on infinity scroll
>  add param lastId to feeds

- database/schemas/UserSchema.js
- migrations/1586530162084-update-user-posting-json-metadata.js
- models/UserModel.js
- utilities/operations/user/importSteemUserOps.js
> add migration to import posting metadata

- constants/postsData.js
- controllers/validators/postValidator.js
- test/controllers/post/test.js
- test/factories/PostFactory/PostFactory.js
- utilities/operations/post/feedCache/hotTrandGetter.js
- utilities/operations/post/getPostsByCategory.js
Task #2260 - excluded some accounts from the Trending
> excluded some accounts from the Trending (@hbd.funder))

- constants/wobjectsData.js
- utilities/operations/wobject/getWobjField.js
Git-2336 deleted news filter from FIELDS_TO_PARSE enum
> Git-2336 deleted news filter

- controllers/validators/wobjectValidator.js
- controllers/wobjController.js
- jobs/collectWobjTopUsers.js
- models/UserWobjects.js
- swagger/swagger.json
- test/controllers/wobject/test.js
- test/factories/ObjectFactory/AppendObjectFactory.js
- test/helpers/cacheAllWobjectExperts/test.js
- test/helpers/wobjectHelper/test.js
- test/testHelper.js
- utilities/helpers/cacheAllWobjectExperts.js
- utilities/helpers/index.js
- utilities/helpers/jsonHelper.js
- utilities/operations/wobject/getWobjField.js
- utilities/operations/wobject/objectExperts.js
Git-2324 fixed display of experts on the object (removed part of code)
> Git-2324 fixed display of experts

- models/wObjectModel.js
Git-2437 added a check if the object is marked as Unavailable do not return it
> Git-2437 added a check for Unavailable objects

- database/schemas/UserWobjectsSchema.js
- models/UserWobjects.js
- test/controllers/wobject/test.js
- utilities/operations/wobject/objectExperts.js
Git-2391 fix sorting by followers and update UserWobjectsSchema
> Git-2391 fix sortings

- test/helpers/wobjectHelper/test.js
- utilities/helpers/wObjectHelper.js
- utilities/operations/wobject/objectExperts.js
Git-2482 display the Reviews tab instead of About when opening a hashtag object from a mobile device
> Git-2482 display the Reviews tab instead of About

- test/models/UserWobjectModel/test.js
Removed tests for "getByWobject" method that was moved from UserWobjectsModel to utilities/operations/wobject/objectExperts.js
> Removed tests in UserWobjectsModel

- utilities/operations/search/globalSearch.js
- utilities/operations/search/searchWobjects.js
Fixed search for existing objects. Escaped reserved Mongo characters.
> Git-2540 Fixed search for existing objects

- utilities/operations/wobject/wobjectInfo.js
The counter was not updated if we delete an object from the current list
> Git-2430 update counter for objects in list

- constants/requestData.js
> wrong children

- utilities/helpers/wObjectHelper.js
Fixed calculation of guest's vote weight
> Git-2568 fixed cause of different names on dining.gifts & pacific.dining.gifts

- constants/wobjectsData.js
- database/schemas/wObjectSchema.js
- test/factories/ObjectFactory/ObjectFactory.js
- test/operations/search/searchWobjects/test.js
- utilities/operations/search/searchWobjects.js
Git-2582 created a text index and changed search queries for full text search
>  Created a text index & changed search queries

- constants/sortData.js
- jobs/index.js
- jobs/updateMaxWobjectWeight.js
- models/wObjectModel.js
- utilities/helpers/sitesHelper.js
- utilities/helpers/wObjectHelper.js
- utilities/operations/post/feedCache/updateCacheOps.js
- utilities/operations/search/searchWobjects.js
- utilities/operations/sites/map.js
- utilities/redis/redisGetter.js
- utilities/redis/redisSetter.js
added a formula for calculating the priority of issuing objects when searching
> Add formula for prioritization on search objects

- utilities/operations/search/searchWobjects.js
Replaced $set on $addFields because in the current version of mongo on staging the $set operator does not exist yet
> Replaced $set on $addFields

- package.json
- utilities/operations/wobject/wobjectInfo.js
- utilities/tasks/addStatusTitles/addStatusTitles.js
- utilities/tasks/addStatusTitles/run.js
added check for availability object status
> Git-2763 removed unavailable wobjects in custom sort list

- constants/regExp.js
- package.json
- utilities/constants.js
- utilities/tasks/updateImagesOnPages/run.js
- utilities/tasks/updateImagesOnPages/updateImagesOnPages.js
created updating links task inside fields.body on pages fields
> Git 2834(pages)

- constants/wobjectsData.js
- utilities/operations/wobject/getManyObjects.js
Added a condition that excludes certain types of objects from searching on Interesting Objects
>  (Git-2961) Fixed object search on "Interesting Objects"

- controllers/validators/sitesValidator.js
- database/schemas/AppSchema.js
- models/wObjectModel.js
- swagger/swagger.json
- test/controllers/wobject/test.js
- test/models/WobjectModel/test.js
changed the storage structure of cities in the field "configuration.availableCities" in App entity
> Update storage structure of cities (For Home Page Task)

- utilities/operations/wobject/getManyObjects.js
added condition excluding unavailable objects
> (Git-2429) Fixed display unavailable objects for the sponsor

- utilities/operations/search/searchWobjects.js
added search by all fields of the object, not just by tag
> (Git-3026) Update search by tags

- utilities/operations/objectType/getOneObjectType.js
- utilities/operations/search/searchWobjects.js
- utilities/operations/wobject/getWobjsNearby.js
Remove deprecated optional field
> Preparing for the MongoDB update
